### PR TITLE
WAC-136: Tidy up UI across devices with a focus on pixel perfection and responsiveness.

### PR DESCRIPTION
**Pull request by ntwalibas**
## Description
This PR, from ticket [WAC-136](https://fjelltopp.atlassian.net/browse/WAC-136), goes through all the work we did during the August 14th sprint to make sure everything is properly aligned, is responsive, and is close to pixel-perfect.
This is with the exception of the sources page which is to be done separately.

Given there are multiple pages and the modifications are mostly subtle, attaching non-comparative screenshots is not a good idea. The commits are quite descriptive for local verification.

## Checklist
- [x] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [x] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [x] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] I have assigned at least one label to this PR: "patch", "minor", "major".

[WAC-136]: https://fjelltopp.atlassian.net/browse/WAC-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
@ntwalibas can you sort a rebase out, handling the conflicts, and then we can review this tomorrow?

**Comment by ChasNelson1990** [comment]
@ntwalibas you can close this without merging now

**Comment by ChasNelson1990** [comment]
@ntwalibas why is this still hanging?

**Comment by ntwalibas** [comment]
My bad @ChasNelson1990. Closed it.

**Pull request closed without merging**
