### PR TITLE
WAC-37 replace all UI references to groups with data types

### PR DESCRIPTION
**Pull request by A-Souhei**
## Description

- Update in ckan/dashboard 
image

- Update in ckan/group
image

- Update in ckan/group/new
image

- Update in ckan/group/<group_name>
image

- Update in ckan/group/edit/<group-name>
image

- Update in titles
image

- Update in left of ckan/dataset
image
image
image

- Also in ckan/group, added margin to 'Add Data Type' button

**Note: When creating a new 'Data Type', it doesn't seem to appear in the ckan/dataset left panel? May be this is the current behavior? Also adding a dataset to a 'Data Type' seems to work but when browsing to ckan/group/<data-type>, we get a NO DATASETS FOUND**

## Checklist

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request).
You may not need to check all boxes.

- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [ ] I have developed these changes in discussion with the appropriate project manager.
- [ ] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [ ] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [ ] I have assigned at least one label to this PR: "patch", "minor", "major".

### CODE REVIEW

**Comment by jonathansberry** [comment]
I'm so sorry, Toavina.  As I am reflecting on this, and reviewing the work you have done, it is making me pause to think more carefully about our use of the "Groups" concept.  I am very clear that Organizations should be renamed to teams - so do continue with that work when you are ready.  However, I am leaning towards keeping the term "Categories" for "Groups" rather than changing to "Data Types". Let's chat on a call when we can.

**Comment by jonathansberry** [comment]
So to be clear - we need to replace all references to "Groups", or "Data Types" to  "Categories"

**Comment by A-Souhei** [comment]
I will work on this ! No problem at all. Basically, I will keep 'Categories' everywhere while changing 'Groups' to 'Category' ? @jonathansberry

**Comment by A-Souhei** [comment]
Ok, I'll fix it.

**Pull request closed without merging**
